#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use ArchFizz\Upnp\GenerateRequestCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new GenerateRequestCommand());
$application->run();
